### ISSUE TITLE
4M downloads?!

### ISSUE THREAD

**Issue by umutgumeli** [jshttp/etag#14]
Just wondering, is it really downloading 4M times in a month or there is a problem?

Great module by the way :heart_decoration:

**Comment by dougwilson** [comment]
Hi @umutgumeli , the number is coming from npm, so I don't 100% know how they calculate number, but my assumption is per month. A lot of people use systems that constantly re-download their dependencies on pushing, so that is likely a large source for the numbers on npm modules :)
