### ISSUE TITLE
Add a link to a definition of ETags in the Readme file

### ISSUE THREAD

**Issue by bwdeep** [jshttp/etag#16]
Presently, there is no context presented for what ETags are, so a simple link to here:
https://en.wikipedia.org/wiki/HTTP_ETag
would solve the problem.

Remember that etags also refers to a program to generate a type of source code map for browsing code in Emacs, so people could be easily confused without the reference.

**Comment by dougwilson** [comment]
Hi @bwdeep, that is an excellent point! Being so HTTP-centric, I never even gave it a second thought :) I'll make this clarification in the documentation and related materials!

**Comment by bwdeep** [comment]
On Wed, Apr 27, 2016 at 10:29 PM, Douglas Wilson <notifications@github.com>
wrote:

> Hi @bwdeep <https://github.com/bwdeep>, that is an excellent point! Being
> so HTTP-centric, I never even gave it a second thought :) I'll make this
> clarification in the documentation and related materials!
>
Good.  Still would be better if you just defined an ETag in the README,
rather than just referencing the RFC.  Imagine you are looking through 10
libraries and you want to know if this is one you should use or not.  You
don't want to go check somewhere else to decide.

Here is an example of text describing a package I am working on publishing
as an example:

Hyperbole is an open, efficient, programmable information management and
hypertext system.  It is intended for everyday work on any UNIX platform
supported by Emacs.  It works well with the versions of Emacs that
support the following window systems: X, Mac OS X, and Windows.

Hyperbole allows hypertext buttons to be embedded within unstructured and
structured files, mail messages and news articles.  It offers intuitive
mouse-based control of information display within multiple windows.  It also
provides point-and-click access to World-Wide Web URLs, Info manuals, ftp
archives, etc., through encapsulations of software that support these
protocols.

Hyperbole consists of four parts:

   1.  Info Management: an interactive information management interface,
       including a powerful contact manager, which anyone can use.  It
       is easy to pick up and use since it introduces only a few new
       mechanisms and provides user-level facilities through a menu
       interface, which you control from the keyboard or the mouse;

   2.  Hypertext Outliner: an outliner with multi-level autonumbering
       and permanent ids attached to each outline node for use as
       hypertext link anchors, plus flexible view specifications that
       can be embedded within links or used interactively;

   3.  Button Types: A set of hyper-button types that provides
       core hypertext and other behaviors.  Users can make simple
       changes to button types and those familiar with Emacs Lisp can
       quickly prototype and deliver new types;

   4.  Programming Library: a set of programming library classes for
       system developers who want to integrate Hyperbole with another
       user interface or as a back-end to a distinct system.  (All of
       Hyperbole is written in Emacs Lisp for ease of modification.
       Although Hyperbole was initially designed as a prototype, it has
       been engineered for real-world usage and is well structured.)

Cheers,

Bob

**Comment by dougwilson** [comment]
> Good. Still would be better if you just defined an ETag in the README, rather than just referencing the RFC. 

Hi @bwdeep, thanks for the feedback! I guess I was confused by literally the title of the issue and your post, which was to add a link. Rather than continuing to try to read your mind, please feel free to make a pull request here with what you would like to see in the readme, and I'm sure we'll accept it :)

**Comment by bwdeep** [comment]
Just add a link to here, with the text, "HTTP ETags are expained here":
https://en.wikipedia.org/wiki/HTTP_ETag.

and make the reference to the RFC be a link that points to page 9 of the
RFC where ETags are defined and then no one should have any questions.

Regards,

Bob

**Comment by dougwilson** [comment]
That wounds good to me! Feel free to make a pull request! With GitHub you can do it without ever leaving the web browser, even :)
