### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by nswbmw** [jshttp/etag#21]
When response body is huge, JSON.stringify throw `RangeError: Invalid string length`. So, 

```
etag = calculate(JSON.stringify(body), options);
```

add simple try...catch will be ok?

```
try {
  etag = calculate(JSON.stringify(body), options);
} catch (e) {}
```

**Comment by dougwilson** [comment]
Hi @nswbmw this module doesn't have any of the code you mentioned above inside it, so I assume you are asking about how to change your own code. You're welcome to write your code however you like :)

**Comment by nswbmw** [comment]
Sorry, 😂 . It's koa-etag, my mistake.
