### ISSUE TITLE
Would you be interested in linking to npmcharts.com for the shields badge? 

### ISSUE THREAD

**Issue by cheapsteak** [jshttp/etag#24]
These currently both link to the npm page

![image](https://user-images.githubusercontent.com/743976/30387275-ffda9b16-9879-11e7-8061-889fa5bf3a18.png)

What do you think about having them link to my site npmcharts.com instead 😛 ?

Link - https://npmcharts.com/compare/etag?minimal=true

Would still look the same, just link to the interactive chart

[![NPM Downloads][downloads-image]][downloads-url]

[downloads-image]: https://img.shields.io/npm/dm/etag.svg
[downloads-url]: https://npmcharts.com/compare/etag?minimal=true

**Comment by dougwilson** [comment]
Hi @cheapsteak seems neat! Yea, they both link to npmjs.org since there wasn't really any link I had for the downloads, but I suppose no longer an issue 👍
