### ISSUE TITLE
Unint8Array Buffer

### ISSUE THREAD

**Issue by jstewart37** [jshttp/etag#25]
Hi,

If i provide etag with a Uint8Array buffer entity, then the validate argument fails. Our temporary workaround is below but i'm sure there must be a better way of doing this.
```js
  // validate argument
  if (!isStats && typeof entity !== 'string' && !Buffer.isBuffer(entity)) {
if (entity.buffer === undefined){
    throw new TypeError('argument entity must be string, Buffer, or fs.Stats')
}
  }
```
Any chance etag can be updated to allow for Uint8Array buffers. 

Thanks

**Comment by dougwilson** [comment]
Yes, please feel free to make a pull request to add support. Don't forget to update the docs and add tests too :+1:

**Comment by dougwilson** [comment]
Closing stale issue. Feel free to make a PR at some point. My understanding is that `Buffer.from` is a current solution:
```
$ node -pe 'require("etag")(Buffer.from("foo"))'
"3-C+7Hteo/D9vJXQ3UfzxbwnXaijM"
$ node -pe 'require("etag")(Buffer.from(new Uint8Array([0x66, 0x6f, 0x6f])))'
"3-C+7Hteo/D9vJXQ3UfzxbwnXaijM"
```
