### ISSUE TITLE
is the usage of sha1 a security vulnerability?

### ISSUE THREAD

**Issue by gaurav5430** [jshttp/etag#29]
my code uses this library as a dependency, and the security tool that i use ([checkmarx](https://www.checkmarx.com/)) flags the use of sha1 as 

> the application protects sensitive data using a cryptographic algorithm, ""sha1"", that is considered weak or even trivially broken

I understand this might be a false positive, so i am just trying to understand whether or not the use of 'sha1' here exposes any security vulnerability.

**Comment by dougwilson** [comment]
The way in which it is uses here it is not that I am aware of.
